Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -12,14 +12,12 @@ jobs:
     timeout-minutes: 30
 
     steps:
-    # Checkout default branch
     - name: Checkout source code
       uses: actions/checkout@v3
 
     - name: Install unzip and curl
       run: sudo apt-get update && sudo apt-get install -y unzip curl
 
-    # Java for SonarCloud
     - name: Set up Java 17
       uses: actions/setup-java@v3
       with:
@@ -78,14 +76,10 @@ jobs:
         scan-ref: .
       continue-on-error: true
 
-    # Checkout Dockerfile branch
     - name: Checkout Dockerfile branch
       uses: actions/checkout@v3
       with:
         ref: feature/docker-setup
-
-    - name: List files (debug)
-      run: ls -la
 
     - name: Docker Hub Login
       uses: docker/login-action@v2
@@ -112,7 +106,6 @@ jobs:
     - name: Push Docker Image
       run: docker push devopscode44/interior-web-app:latest
 
-    # Checkout Helm chart branch
     - name: Checkout Helm Chart
       uses: actions/checkout@v3
       with:
@@ -135,31 +128,36 @@ jobs:
           --create-namespace
 
     - name: Wait for ALB Ingress DNS
+      id: get-dns
       run: |
         echo "Waiting for ALB DNS..."
         for i in {1..30}; do
           DNS=$(kubectl get ingress flask-app -n default -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
           if [[ "$DNS" != "" ]]; then
             echo "ALB DNS: $DNS"
-            echo "DNS=$DNS" >> $GITHUB_ENV
+            echo "dns=$DNS" >> "$GITHUB_OUTPUT"
             break
           fi
           echo "Still waiting ($i)..."
           sleep 10
         done
+        if [[ -z "$DNS" ]]; then
+          echo "DNS not found after timeout."
+          exit 1
+        fi
 
     - name: Patch Ingress Host
       run: |
         kubectl patch ingress flask-app -n default \
           --type=json \
-          -p='[{"op": "replace", "path": "/spec/rules/0/host", "value": "flask-app.${{ env.DNS }}.nip.io"}]'
+          -p='[{"op": "replace", "path": "/spec/rules/0/host", "value": "flask-app.${{ steps.get-dns.outputs.dns }}.nip.io"}]'
 
     - name: Print Access URL
       run: |
-        echo "App deployed at: https://flask-app.${{ env.DNS }}.nip.io"
+        echo "App deployed at: https://flask-app.${{ steps.get-dns.outputs.dns }}.nip.io"
 
     - name: Save DNS URL as artifact
-      run: echo "https://flask-app.${{ env.DNS }}.nip.io" > app-url.txt
+      run: echo "https://flask-app.${{ steps.get-dns.outputs.dns }}.nip.io" > app-url.txt
 
     - name: Upload App URL
       uses: actions/upload-artifact@v4
